<?php

return [
    'word_variables' => ['client', 'create_date', 'service', 'price', 'date', 'expiration_date'],
    'dashboard_models' => ['template', 'client', 'service', 'price'],

    'admin_select_cols' => ["id", "username", "is_admin"],
    'admin_table_cols' => ["id", "username", "is_admin"],
    'client_select_cols' => ["id", "name", "address"],
    'contract_select_cols' => ["id", "client_id", "is_active", "word_link", "pdf_link"],
    'log_select_cols' => ["id", "table", "ip_address", 'action', 'user_id'],
    'price_select_cols' => ["id", "price", "price_words", "currency"],
    'price_table_cols' => ["id", "price", "price_words", "currency"],
    'service_select_cols' => ["id", "name", "description"],
    'service_table_cols' => ["id", "name", "description"],
    'template_select_cols' => ["id", "name"],
    'template_table_cols' => ["id", "name"],
    'domain_select_cols' => ['domains.id', 'domains.name', 'domains.type', 'domains.registrar', 'domains.user', 'domains.has_access', 'domains.client_id', 'clients.name as client_name'],
    'hosting_select_cols' =>['hostings.id','hostings.client_id','hostings.package_name','clients.name as client_name'],

    'admin_index_th_values' => ["ID", "Korisničko ime", "Akcije"],
    'admin_index_td_values' => ["id", "username"],
    'client_index_th_values' => ["ID", "Ime", "Adresa", "Akcije"],
    'client_index_td_values' => ["id", "name", "address"],
    'client_show_th_values' => ["ID", "Ime", "Adresa", "OIB", "Predstavnik", "Vezna oznaka", "Vrsta partnera", "Telefon", "E-mail adresa", "Prodavač", "Aktivnosti", "Grad", "Država"],
    'contract_index_th_values' => ["ID", "Klijent", "Aktivan", "Akcije"],
    'contract_index_td_values' => ["id", "client_name", "is_active"],
    'contract_show_th_values' => ["ID", "Datum početka usluge", "Datum isteka usluge", "Ime predloška", "Cijena", "Usluga", "Word", "Kreirao", "Datum potpisa ugovora", "Napomena", "Klijent", "PDF link", "Aktivan", "Vidljiv svima", "Kreirano", "Ažurirano"],
    'contract_show_td_values' => ["id", "starting_date_display", "expiration_date_display", "template_name", "price_value", "service_description", "word_link", "username", "signing_date_display", "note", "client_name", "pdf_link", "is_active", "is_visible_to_all", "created_at_display", "updated_at_display"],
    'price_index_th_values' => ["ID", "Cijena", "Cijena (riječima)", "Valuta", "Akcije"],
    'price_index_td_values' => ["id", "price", "price_words", "currency"],
    'service_index_th_values' => ["ID", "Ime", "Usluga", "Akcije"],
    'service_index_td_values' => ["id", "name", "description"],
    'template_index_th_values' => ["ID", "Ime", "Akcije"],
    'template_index_td_values' => ["id", "name"],
    'log_index_th_values' => ["ID zapisa", "Resurs kreirao/la", "Tablica", "Akcija", "IP adresa", "Akcije"],
    'log_index_td_values' => ["id", "username", "table", "action", "ip_address"],
    'log_show_th_values' => ["ID zapisa", "Resurs kreirao/la", "ID resursa", "Tablica", "Akcija", "IP adresa", "Zapis kreiran"],
    'log_show_td_values' => ["id", "username", "resource_id", "table", "action", "ip_address", "updated_at_display"],
    'dashboard_th_values' => ["Predlošci", "Klijenti", "Usluge", "Cijene"],
    'dashboard_template_td_values' => ['id', 'name'],
    'dashboard_client_td_values' => ['id', 'name'],
    'dashboard_service_td_values' => ['id', 'name'],
    'dashboard_price_td_values' => ['id', 'price', 'currency'],

    'domain_index_th_values' => ['ID', 'Klijent', 'Ime domene', 'Vrsta domene', 'Registrar', 'Korisnik', 'Pristup dozvoljen?', 'Akcije'],
    'domain_index_td_values' => ['id', 'client_name', 'name', 'type', 'registrar', 'user', 'has_access_display'],
    'domain_show_th_values' => ['ID', 'Ime domene', 'Vrsta domene', 'Registrar', 'Korisnik', 'Pristup dozvoljen?', 'Preusmjereno?', 'Preusmjereno na:', 'Klijent', 'Datum isteka'],
    'domain_show_td_values' => ['id', 'name', 'type', 'registrar', 'user', 'has_access_display', 'is_redirected_display', 'is_redirected_where', 'client_name', 'expires_at_display'],

    'hosting_index_th_values' => ['ID', 'Klijent', 'Naziv paketa', 'Akcije'],
    'hosting_index_td_values' => ['id', 'client_name', 'package_name'],
    'hosting_show_th_values' => ['ID', 'Ime klijenta', 'Naziv paketa', 'Opis paketa', 'Cijena', 'Datum isteka hostinga'],
    'hosting_show_td_values' => ['id', 'client_name', 'package_name', 'package_description', 'price', 'expiration_date_formatted'],
    'num_of_payments' => 3,
    'payments_filter_values' => ['client_id', 'start_month', 'start_year', 'end_month', 'end_year'],
];
